### ISSUE TITLE
shuffle_sequence truncated

### ISSUE THREAD

**Issue by Mjaraespejo** [bjmt/universalmotif#1]
Hi, I am trying to use the shuffle_sequence function from the universalmotif package in order to shuffle a data containing ~19300 fasta sequeunces of 50 nt length. When I run my script using jus 10 sequences it works perfectly, but when I tried to used with the big data I get this error message : 
fastaFile = readDNAStringSet("m6A_5-3-sequences.fasta")
euler <- shuffle_sequences(fastaFile, k = 2, method = "euler")

Error in edgematrix[i, alph.i[lastlets[[i]]]] : 
  incorrect number of dimensions

**Comment by bjmt** [comment]
Hmm. Would you mind trying the development version? The internal shuffle_sequences() code has been completely rewritten.

```
BiocManager::install("universalmotif", version = "devel")
```

If this still doesn't work, please send me some example sequences which trigger this error. If I were to guess, it has to do with unrecognised characters, but it's hard to tell without seeing the fasta file.

**Comment by bjmt** [comment]
New Bioconductor release, which means your question is likely now outdated. Feel free to reopen if you still run into problems with the new version.
