### ISSUE TITLE
[JOSS REVIEW] No community/contribution guidelines

### ISSUE THREAD

**Issue by chrisamiller** [bjmt/universalmotif#27]
This project lacks community guidelines, as described in the JOSS review checklist.  

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

A CONTRIBUTING.md file would solve this easily enough

**Comment by bjmt** [comment]
A CONTRIBUTING.md file has been created with guidance on opening issues and pull requests, as well as directing users needing help to the Bioconductor support site. Please let me know if you find this suitable or have additional advice.
